recruiter/authentication/urls.py
from django.conf.urls import url

from . import views

app_name = 'authentication'
urlpatterns = [
    url(r'^login/$', views.sign_in, name='login'),
    url(r'^logout/?$', views.logout_view, name='logout'),
    url(r'^signup/?$', views.sign_up, name='signup')
]

recruiter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from recruiter.core import views as core_views

urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'', include('recruiter.authentication.urls')),
    url(r'^admin/', admin.site.urls)
]

recruiter/authentication/models.py
from django.db import models

# Create your models here.

recruiter/core/models.py
from django.db import models

# Create your models here.

recruiter/authentication/forms.py
from django import forms
from django.contrib.auth.models import User


class SignUpForm(forms.ModelForm):
    email = forms.EmailField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    repeat_password = forms.CharField(max_length=200, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password', 'repeat_password', ]

    def clean_repeat_password(self):
        password = self.cleaned_data.get("password")
        repeat_password = self.cleaned_data.get("repeat_password")

        if password and repeat_password and password != repeat_password:
            raise forms.ValidationError("Password don't match.")

        return repeat_password

    def save(self):
        super().clean()

        return User.objects.create_user(
            username=self.cleaned_data.get('email'),
            email=self.cleaned_data.get('email'),
            password=self.cleaned_data.get('password'))

recruiter/authentication/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout

from .forms import SignUpForm


def sign_in(request):
    if request.method == 'POST':
        username = request.POST.get('userName')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next')
            return redirect(next_url if next_url is not None else reverse('recruiter:home'))
        else:
            auth_error = "Wrong credentials. User hasn't been found"
            return render(request, 'authentication/login.html', {'auth_error': auth_error})
    else:
        return render(request, 'authentication/login.html')


def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()
            if user is not None:
                login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()

    return render(request, 'authentication/signup.html', {'form': form})


def logout_view(request):
    if request.user.is_authenticated:
        logout(request)

    return redirect(reverse('recruiter:home'))

recruiter/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'core/home.html')

recruiter/authentication/templates/authentication/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Please sign in</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <h3 style="color: red;">{{ auth_error }}</h3>
        <input type="text" placeholder="Type your name" name="userName">
        <input type="password" placeholder="Type your password" name="password">
        <button type="submit">Sign In</button>
    </form>
</body>
</html>

recruiter/authentication/templates/authentication/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign up my friend</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Register</button>
    </form>
</body>
</html>

recruiter/core/templates/core/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
</head>
<body>
    <h1>Nice to meet you in this fantastic application</h1>
    <h3>Please feel free:</h3>
    <a href="{% url 'authentication:login' %}">Sign In</a>
    <h3>OR</h3>
    <a href="{% url 'authentication:signup' %}">Sign Up</a>
</body>
</html>